// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Roller2;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_bleon2_png);   // assets\bleon2.png
LV_IMG_DECLARE( ui_img_364787093);   // assets\hour_50h-2.png
LV_IMG_DECLARE( ui_img_minute_80_png);   // assets\minute_80.png
LV_IMG_DECLARE( ui_img_1387450172);   // assets\minute_80h-2.png
LV_IMG_DECLARE( ui_img_people1_png);   // assets\people1.png
LV_IMG_DECLARE( ui_img_people2_png);   // assets\people2.png
LV_IMG_DECLARE( ui_img_second_120_png);   // assets\second_120.png
LV_IMG_DECLARE( ui_img_827571443);   // assets\second_120h-2.png
LV_IMG_DECLARE( ui_img_up2_png);   // assets\up2.png
LV_IMG_DECLARE( ui_img_wifioff2_png);   // assets\wifioff2.png
LV_IMG_DECLARE( ui_img_wifioff_40_png);   // assets\wifioff_40.png
LV_IMG_DECLARE( ui_img_wifioff_45_png);   // assets\wifioff_45.png
LV_IMG_DECLARE( ui_img_wifion2_png);   // assets\wifion2.png
LV_IMG_DECLARE( ui_img_171461417);   // assets\xiao-30.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
