// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"

void ui_comp_Arc2_create_hook( lv_obj_t * comp)
{
}

void ui_comp_Panel2_create_hook( lv_obj_t * comp)
{
}

void ui_comp_run_create_hook( lv_obj_t * comp)
{
}
